### ISSUE TITLE
Support for Office 365 calendars

### ISSUE THREAD

**Issue by ziolko** [roombelt/roombelt#1]

**Comment by Mo-O** [comment]
Will be there support for Exchange 2016 in the future?

**Comment by ziolko** [comment]
Hi, support for Exchange is next on my list and most probably it will be there in January.

**Comment by ziolko** [comment]
This turned out to be more complex that I originally thought. I will first focus on support for Office365 and only when it's done I will work on Exchange support.

**Comment by creed205** [comment]
Hi @ziolko!

Looks like a great project. I too am looking for something that integrates into Office365. If you need any assistance testing, please let me know.

**Comment by ziolko** [comment]
Hi @creed205,

After recent changes in Roombelt architecture adding support for Office365 will be pretty straightforward. In the next few days I plan to release a beta version that early adopters can try. I will keep you updated!

**Comment by creed205** [comment]
Thanks! Can’t wait to see it.

Marcus Hamaker
e: marcus@hamaker.net<mailto:marcus@hamaker.net>
c: 514.497.8659

**Comment by creed205** [comment]
Installation might be a bit of a challenge for me. I am not sure how to go from GIT to my android device. I assume I need to do an on premis? Cloud not ready just yet?

**Comment by ziolko** [comment]
I'd recommend to wait for Cloud version to be on production. Yesterday I've got a working version on dev environment but I need to test it end-to-end. Depending on what the tests reveal it should take no more than a few days before releasing it.

**Comment by creed205** [comment]
Great - thank you!

**Comment by ziolko** [comment]
@creed205, @Mo-O - support for Office365 calendars has just been deployed to [app.roombelt.com](https://app.roombelt.com).

Due to Office365 permissions system the app needs admin's consent to modify calendars of people in your organization. If you don't have an admin account you should ask your admin to sign in to Roombelt. Once he signs in you will be able to sign in as well.

You may notice that Roombelt shows organizer name instead of meeting subject. This is a known behavior of Office365 and a sample solution can be found [here](https://robinpowered.com/blog/how-to-fix-event-titles-for-meeting-room-events-in-office-365-and-exchange/).

I am working on documentation for Office365 integration. If you encouter any issues please let me know!

Thanks,
Mateusz

**Comment by ziolko** [comment]
@creed205, @Mo-O As this functionality has been delivered I am closing this issue. If you find any problems with Office365 integration please raise a new ticket.
