### ISSUE TITLE
Show available rooms on the dashboard

### ISSUE THREAD

**Issue by saz** [roombelt/roombelt#13]
As far as I can see, available rooms are not shown on the dashboard.
Might be good, to find an available room quickly.

Maybe make it configurable, to show available rooms or not on the dashboard.

**Comment by ziolko** [comment]
I really like this idea. I think I will deliver this in the next 3 weeks.

**Comment by saz** [comment]
Hey @ziolko any news on this? Can I help you in any way?

**Comment by ziolko** [comment]
HI @saz. I didn't manage to implement this yet, but as this is a fairly simple feature I will prioritize this to deliver by the end of weekend.

Sorry for the delay.
Mateusz

**Comment by ziolko** [comment]
@saz, this functionality has been deployed to production today. You can enable option "highlight available rooms" for dashboard device in the admin panel (https://app.roombelt.com/admin).

Please refresh Roombelt on dashboard device after setting this option and let me know if this issue can be closed.

**Comment by saz** [comment]
@ziolko Works great! Thanks for the fast implementation!
