### ISSUE TITLE
Multiple Dashboard devices - alternate Name?

### ISSUE THREAD

**Issue by saz** [roombelt/roombelt#14]
If you're setting up multiple dashboard devices, all of them will have the same name, which makes it hard to distinguish.

An alternate name for dashboard devices would be good!

**Comment by ziolko** [comment]
Thanks for this request. Do you think this name should be visible on the device display or it's just for administration purpose?

**Comment by saz** [comment]
Just for administrative purposes.

**Comment by ziolko** [comment]
Ok, I will implement it soon.

**Comment by saz** [comment]
:+1:

**Comment by ziolko** [comment]
@saz, I added a "location" option for dashboard devices. Once set it appears as a device name on list of devices. Please let me know if it works for you.

As a side note - I feel the admin panel is now cluttered with several options. I plan to spend some time in the future to redesign it.

**Comment by saz** [comment]
Thanks for this. I don't have the feeling, that the admin panel is cluttered but I'm curious what you're working out.
