### ISSUE TITLE
Enable fullscreen using a URL paramter?

### ISSUE THREAD

**Issue by saz** [roombelt/roombelt#15]
We're running roombelt on some devices with no input capability.

Using e.g. the dashboard shows a fullscreen button at the bottom corner.

Is there any way of hiding this button?

**Comment by ziolko** [comment]
Hi @saz,

Is this issue about hiding the fullscreen button that is useless for you, or is it about showing Roombelt always in fullscreen without the need for user to click the "fullscreen" button?

Don't you mind sharing what are the devices without input capability?

**Comment by saz** [comment]
Hiding the button would be enough. We're using raspberry pis asdigital signage displays without a mouse or a keyboard connected.
-- 
Diese Nachricht wurde mit <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> gesendet.

**Comment by ziolko** [comment]
Ok, so I deployed a new version that shows the "full screen" button only for 1 minute. Please refresh roombelt on your device and wait 1 minute - the button should disappear.

Please let me know if it works for you,
Mateusz

**Comment by saz** [comment]
Looks good, thanks!
-- 
Diese Nachricht wurde mit <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> gesendet.
