### ISSUE TITLE
Rejected appointments shown on room dashboard

### ISSUE THREAD

**Issue by saz** [roombelt/roombelt#16]
If there is an appointment at for example 3pm and another one booked at the same time, the room resource will reject the second appointment, but it will still be visible in the room calendar but as rejected.
If you're ending the first meeting early, the other appointment will be shown as "Started x mins ago" and you're able to check in.

**Comment by ziolko** [comment]
@saz that's definitely a bug. I will filter out rejected meetings by the end of the week.

**Comment by ziolko** [comment]
@saz I've deployed a new version and this should be fixed now. Could you please confirm that this issue can be closed?

**Comment by ziolko** [comment]
@saz, do you still experience this issue?

**Comment by saz** [comment]
Sorry for not responding earlier.
I'm not able to reproduce this right now, so I think it's resolved :-)
