### ISSUE TITLE
Make checkin time configurable

### ISSUE THREAD

**Issue by saz** [roombelt/roombelt#17]
Right now, it's possible to check-in 5 minutes before a meeting starts.
It would be good if this is configurable

**Comment by ziolko** [comment]
Hi @saz, what would be your preference for the check-in time?

**Comment by saz** [comment]
I'd really go with a configurable check-in time. For us, we're used to 15mins before a meeting starts, but this might not be the case for all people.
Making it possible to select between 5, 10 or 15mins should fit most people

**Comment by ziolko** [comment]
I see your point. This will be the next thing I will be working on.

**Comment by ziolko** [comment]
@saz I've just deployed a new version with this functionality. If you edit connected devices at [app.roombelt.com/admin](https://app.roombelt.com/admin) you should see a new "start early" option. 

You need to reload (refresh) Roombelt on your devices to make this setting work on them. 

Please let me know if it meets your needs,
Mateusz

**Comment by saz** [comment]
Awesome thanks! Exactly what we needed
