### ISSUE TITLE
Click/touch events

### ISSUE THREAD

**Issue by lociii** [roombelt/roombelt#30]
Hey Mateusz,

as you know RegioHelden is a happy customer. So first, thanks for all the work/effort you put into this project and your fast feeback!

One thing we recognized lately is that the event handlers on the buttons (like checkin, end meeting, etc) don't always properly react on click if you the finger is slightly moved when touching the button.
Is there any other type of event that the system might listen to to catch these "clicks"?

Thanks, Jens

**Comment by ziolko** [comment]
Hi @lociii,

That's a great catch! I will ensure that this issue is fixed by the end of the week.

Regards,
Mateusz

**Comment by ziolko** [comment]
@lociii I've deployed a new version that is supposed to fix this issue. You will need to refresh Roombelt on your devices to benefit from the new behavior.

Let me know if it works as expected now.

**Comment by lociii** [comment]
Way better now. Thanks a lot!
Keep up the great work.
