### ISSUE TITLE
change apple-mobile-web-app-status-bar-style to "black" or "black-translucent"?

### ISSUE THREAD

**Issue by wliao229** [roombelt/roombelt#35]
The iOS status bar is current white-backgrounded, which looks quite inconsistent to the current dark theme. Could this be changed to "black" or "black-translucent"?

https://github.com/roombelt/roombelt/blob/4d14f8aa8f19317c296c5e999cf9a4ac4e91a3a2/frontend/public/index.html#L10

**Comment by ziolko** [comment]
@wliao229 I've just deployed a new version with this tag set to `black-translucent`.

**Comment by wliao229** [comment]
Thanks.

On Aug 4, 2019, at 1:19 PM, Mateusz Zieliński <notifications@github.com<mailto:notifications@github.com>> wrote:


@wliao229<https://github.com/wliao229> I've just deployed a new version with this tag set to black-translucent.

**Comment by wliao229** [comment]
Could you update the docker image as well?

**Comment by ziolko** [comment]
I've just deployed a new version of docker image.

Please be informed that I plan to release Roombelt 2.0 On-Premises in the next few weeks that will follow [Cloud pricing](https://roombelt.com). Unfortunately, it turned out users are not open to buy a subscription if it's optional 😉
